### PR TITLE
Fix AudioThread crash on exit

### LINKED ISSUE #244: AudioThread occasionally crashes on exit
After some debugging, this seems to be caused by the audio thread accessing `audio::midiout` after it has been [deleted](https://github.com/Attnam/ivan/blob/fca7cb172df3ae20648a6ad484e0b1e64923a299/audio/audio.cpp#L151) by the main thread (`audio::DeInit` is registered to `std::atexit`). Stack trace:

```
(lldb) bt
* thread #6, name = 'AudioThread', stop reason = EXC_BAD_ACCESS (code=1, address=0x102ebaff8)
  * frame #0: 0x0000000100920b04 libFeAudio.dylib`RtMidiOut::sendMessage(this=0x0000000102ebaff0, message=0x00000001042fff90 size=3) at RtMidi.h:561
    frame #1: 0x0000000100920adc libFeAudio.dylib`audio::SendMIDIEvent(message=0x00000001042fff90 size=3) at audio.cpp:436
    frame #2: 0x000000010091fb15 libFeAudio.dylib`::SendMIDIEvent(event=0x0000000104300a78) at audio.cpp:473
    frame #3: 0x00000001009247b5 libFeAudio.dylib`::MPB_PlayEvent(event=0x0000000104300a70, mode=MPB_PB_NO_VOL) at midiplayback.cpp:817
    frame #4: 0x00000001009257d7 libFeAudio.dylib`::MPB_ProcessGenericEvent(MIDIHdr=0x0000000104300410, track=0x0000000104300a58, event=0x0000000104300a70, mode=MPB_PB_NO_VOL) at midiplayback.cpp:436
    frame #5: 0x0000000100925598 libFeAudio.dylib`::MPB_PlayTrack(MIDIHdr=0x0000000104300410, track=0x0000000104300a58, mode=MPB_PB_NO_VOL) at midiplayback.cpp:524
    frame #6: 0x0000000100924c7c libFeAudio.dylib`::MPB_ContinuePlay(MIDIHdr=0x0000000104300410, mode=MPB_PB_NO_VOL) at midiplayback.cpp:400
    frame #7: 0x000000010091e91e libFeAudio.dylib`audio::PlayMIDIFile(filename="/usr/local/share/ivan/Music/mainmenu.mid", loops=1) at audio.cpp:346
    frame #8: 0x000000010091dafe libFeAudio.dylib`audio::Loop(ptr=0x0000000000000000) at audio.cpp:174
    frame #9: 0x0000000100ab1306 libSDL2-2.0.0.dylib`SDL_RunThread + 60
    frame #10: 0x0000000100aeec9b libSDL2-2.0.0.dylib`RunThread + 9
    frame #11: 0x0000000100bb9bc8 libsystem_pthread.dylib`_pthread_body + 180
    frame #12: 0x0000000100bb9b14 libsystem_pthread.dylib`_pthread_start + 286
    frame #13: 0x0000000100bb92fd libsystem_pthread.dylib`thread_start + 13
```

### PR DESCRIPTION
**Pull request by fejoa**
Fixes #244

### CODE REVIEW

File: audio/audio.cpp [hunk 1]
```diff
@@ -139,6 +139,7 @@ void audio::Init(cfestring& musicDirectory)
 
 void audio::DeInit(void)
 {
+  audio::SetPlaybackStatus(audio::STOPPED);
```
Comment (emlai) [inline audio/audio.cpp]: *cough* indentation *cough* 😉 

(also the `audio::` prefixes aren't needed)
